### ISSUE TITLE
Is it possible to include any kind/number of data in event window?

### ISSUE THREAD

**Issue by tashimaya** [timeglider/jquery_widget#21]
Hi

I've just discovered Timeglider and I'm playing with the following demo:

http://timeglider.com/jquery/large.html

When you click on a timeline event, a little window pops up.  It may contain an image, a description and a link.

Does Timeglider have an ability to allow user to change its size and include any kind/number of data in this window?

For example, I'd like to include a YouTube video, a list of links and several images and so on.

Also, I've noticed a tooltip can remain on the timeline if you zoom in while it's being displayed.

Thanks for creating this amazing jQuery plugin!

**Comment by apshoemaker** [comment]
From my limited use of the plugin so far, it seems that the description field does not escape any html, so as long as it is part of the same string, it should show up.

**Comment by timeglider** [comment]
You can include any HTML in that data — yes (though in our app at timeglider.com, it will be a lot more restricted.  So you can add iFrames for video, or whatever. You can also add other data points into the JSON and have those available. As far as the size of the modal, that's changable too with CSS. Since this was posted, we also have a "modal_type" that can be set to "full" — either in the widget options (for doing it for all events), or per-event for stuff that has images, longer descriptions, etc.
