### ISSUE TITLE
How could change the date settings?

### ISSUE THREAD

**Issue by janstieler** [timeglider/jquery_widget#5]
HI,
how could I change the datesettings? I need a one year range from january to dezember without a year.

Best regards

**Comment by timeglider** [comment]
Every event, being on a precise horizontal axis, needs to have a start date ("startdate"). If it's a range, you need "enddate" as well --- including year, month, day, and even time.  That said, you don't need to _display_ the date at all (on hover, in the details modal). I've just updated a few files to, first change the "date_limit" property in the JSON to "date_display" (see the JSON page in my docs: http://timeglider.com/jquery/?p=json) In the JSON for that event object, you could add this line:
     "date_display":"none" 
and no date would be shown.

**Comment by janstieler** [comment]
Hi,
sorry I was not precise enough.
I mean not the date in the modal but I mean the timeaxis.
In this I need a axis from january to december. Is there a option to set this?

BR

**Comment by talamaska** [comment]
i got the same question, is it based on max and min date of all events?

**Comment by timeglider** [comment]
if it's the view you're talking about (rather than a specific timeline), setting the focus date of the timeline being loaded, in combination with the zoom level, is what sets the overall scope. Right now, there's no method to set the timeline to a focus/scope based on start end dates ------ it's what's set in the middle.  A lot of this depends on the width of your container div, too.

**Comment by xiunen** [comment]
i have the same problem, i want make the timeaxis as precise as seconds/minutes level.
