### ISSUE TITLE
events duplicated until move titleBar

### ISSUE THREAD

**Issue by carlospictor** [timeglider/jquery_widget#50]
Strange bug appearing here:

http://hantsweb-staging.hants.gov.uk/timeglider

Scroll back to about 1200, and you'll see 'Winchester moot horn made in this period' is duplicated, with one sitting messily under another event.

Moving the titleBar causes those events to redraw and the erroneous entry to vanish.  

Any thoughts on how I can prevent this in the first place?  I've tried adding extra listeners in jquery to move the titleBar on load, but that doesn't help.

**Comment by timeglider** [comment]
Clearly there is an issue with moot horns.

Actually, this looks familiar: When panning left, the
right side of spans that cross from one "tick" to another are
initiated by the righthand tick, but the system needs to register
that they have been added so that when leftward (startdate)
tick is added, it doesn't try to add them again.  I though I had this
worked out: When is the last time you downloaded the TG code?
In my local tests, the problem doesn't seem to be occurring.

Note to self: keep a better changelog!

••••••••••••••••••••••••••••••
co-founder, lead developer
_www.timeglider.com_
michael@timeglider.com
cell 208.850.8512
twitter @timeglider
••••••••••••••••••••••••••••••

On Wed, Jun 6, 2012 at 2:57 AM, carlospictor <
reply@reply.github.com

**Comment by carlospictor** [comment]
Hi,

Many thanks for quick response.

I download the TG code only a couple of weeks ago, using timeglider-0.1.3.min.js - setting up and using a timeglider was a joy. Other than this tiny niggle I think it's perfect!

I've just updated my script from the latest version here, but it doesn't make a difference.

Is timeglider-0.1.3.min.js the latest version I should be using?

**Comment by timeglider** [comment]
I've created a draft 0.1.4 min file ----- attached.  See how this
works for you.  We have a new collision detection and (as I
described) cache of placed spans...

I'm still optimizing the collision detection ---- let me know if it
gets gummed up with your large set of data.

Have you thought about prioritizing your events so that when
one zooms out, a smaller set (of more important) events shows?

On Wed, Jun 6, 2012 at 8:49 AM, carlospictor <
reply@reply.github.com

**Comment by carlospictor** [comment]
Hi,

Thanks for the 0.1.4 file. That definitely fixes the issue of duplicates - thank you.

The only downsides though are that the event modal now jumps around the timeglider, often being cut-off by the container, and the timeglider isn't draggable on iPad anymore - touching the timeline even subtly jumps to -7041257 9or thereabouts).

I tried comapring the positioning of the modal between versions 0.1.3 and 0.1.4 - but this is a level of javascript beyond my hacking skills!

Thanks though anyway :o)

**Comment by timeglider** [comment]
Okay ------ rats. Something else happened in the
transition; I'll do some wider testing with modals
and on the iPad. Back to 0.1.3 for now, I guess!

On Thu, Jun 7, 2012 at 6:30 AM, carlospictor <
reply@reply.github.com
