### ISSUE TITLE
how to draw continues bar with startdate but without enddate

### ISSUE THREAD

**Issue by shioc** [timeglider/jquery_widget#53]
Hi there, so sorry to bother, am using the time glider to set up support resource plan, 

We have some permanent resources that have constantly in the gilder and some have start and enddate 
Ideally the permanent resources will have the continues bar, and the temporay will have start and end dates. 

However am having problem to draw the bar with only a startdate. 

Is that anyway I can do that?

**Comment by timeglider** [comment]
Try putting "today" in the enddate field -------- that generates the current date-time when the timeline is loaded. We're working on a way to indicate that not only is the enddate today, but it needs to constantly update (in real time).  None of it's documented because it feels a little mushy still; but using "today" as the enddate will be a permanent element.
